# https://github.com/assimp/assimp/blob/master/Build.md

name: 5.0.1-r$(rev:r)

trigger:
 tags:
   include:
    - v5.0.1

pr:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  
- script: sudo apt-get install cmake
  displayName: Install CMake

- script: |
    cmake CMakeLists.txt 
    cmake --build .

